databases:
  - name: course-db
    plan: free
    databaseName: course
    user: course

services:
  - type: web
    plan: free
    name: course-sp
    runtime: docker
    dockerfilePath: Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: JDK_JAVA_OPTIONS
        value: -Xms256m -Xmx512m -Dspring.profiles.active=prod
      - key: DATABASE_URL
        fromDatabase:
          name: course-db
          property: connectionString
    numInstances: 1